#!/usr/bin/env python3
"""
Parse DP_PushT.log and generate training_data.js for GitHub Pages visualization.
Usage: python parse_log.py
Output: training_data.js
"""

import re
import json

def parse_k(value_str):
    """Parse '26K' → 26000, '10M' → 10000000, '0.24' → 0.24"""
    value_str = value_str.strip()
    if value_str.endswith('K'):
        return float(value_str[:-1]) * 1000
    elif value_str.endswith('M'):
        return float(value_str[:-1]) * 1_000_000
    else:
        return float(value_str)

def clean_line(line):
    """Remove ANSI escape sequences and terminal control chars."""
    # Remove ANSI escape sequences like ESC[...m, ESC[?...
    ansi_escape = re.compile(r'\x1b\[[0-9;?]*[a-zA-Z]')
    line = ansi_escape.sub('', line)
    # Remove remaining control chars (like ^[[B for cursor up)
    line = re.sub(r'\^\[\[[A-D]', '', line)
    line = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', '', line)
    return line

def parse_log(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    # Clean lines
    clean_lines = []
    for line in lines:
        cleaned = clean_line(line.strip())
        if cleaned:
            clean_lines.append(cleaned)

    full_text = '\n'.join(clean_lines)

    # Extract training config from log header
    config = {
        'task': 'PushT',
        'model': 'Diffusion Policy',
        'framework': 'LeRobot (HuggingFace)',
        'total_steps': 80000,
        'num_params': '278M',
        'batch_size': 64,  # effective: 32 × 2 GPUs
        'batch_size_per_gpu': 32,
        'num_gpus': 2,
        'dataset_frames': 105480,
        'dataset_episodes': 81,
        'lr_scheduler': 'Cosine with 500 warmup steps',
        'num_inference_steps': 20,
        'num_train_timesteps': 100,
        'n_action_steps': 32,
        'n_obs_steps': 2,
        'eval_freq': 10000,
        'eval_episodes': 50,
        'output_dir': 'outputs/train/diffusion_viola_PushT',
    }

    # Parse training step lines
    # Pattern: step:200 smpl:26K ep:20 epch:0.24 loss:0.515 grdn:3.254 lr:2.0e-05 updt_s:0.296 data_s:0.132
    step_pattern = re.compile(
        r'step:(?P<step>\S+)\s+'
        r'smpl:(?P<smpl>\S+)\s+'
        r'ep:(?P<ep>\S+)\s+'
        r'epch:(?P<epch>\S+)\s+'
        r'loss:(?P<loss>\S+)\s+'
        r'grdn:(?P<grdn>\S+)\s+'
        r'lr:(?P<lr>\S+)\s+'
        r'updt_s:(?P<updt_s>\S+)\s+'
        r'data_s:(?P<data_s>\S+)'
    )

    metrics = []
    for line in clean_lines:
        m = step_pattern.search(line)
        if m:
            try:
                entry = {
                    'step': int(parse_k(m.group('step'))),
                    'samples': int(parse_k(m.group('smpl'))),
                    'episodes': int(parse_k(m.group('ep'))),
                    'epoch': round(parse_k(m.group('epch')), 2),
                    'loss': parse_k(m.group('loss')),
                    'grad_norm': parse_k(m.group('grdn')),
                    'lr': float(m.group('lr')),
                    'update_time_s': parse_k(m.group('updt_s')),
                    'data_time_s': parse_k(m.group('data_s')),
                }
                metrics.append(entry)
            except (ValueError, IndexError):
                continue

    # Extract start/end time
    start_match = re.search(r'INFO (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*Start offline training', full_text)
    end_match = re.search(r'INFO (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*End of training', full_text)

    if start_match:
        config['training_start'] = start_match.group(1)
    if end_match:
        config['training_end'] = end_match.group(1)

    # Training summary
    if metrics:
        config['final_loss'] = f"{metrics[-1]['loss']:.4f}"
        config['final_grad_norm'] = f"{metrics[-1]['grad_norm']:.4f}"
        config['total_epochs'] = f"{metrics[-1]['epoch']:.1f}"
        config['total_records'] = len(metrics)

    return config, metrics

def write_js(config, metrics, output_path):
    """Write training_data.js with TRAINING_DATA global variable."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by parse_log.py - DO NOT EDIT MANUALLY\n')
        f.write('// Contains training metrics and config for Diffusion Policy reproduction\n')
        f.write('const TRAINING_DATA = ')
        f.write(json.dumps({'config': config, 'metrics': metrics}, indent=2, ensure_ascii=False))
        f.write(';\n')
    print(f'[OK] Written {len(metrics)} training records to {output_path}')
    print(f'  Config keys: {list(config.keys())}')

if __name__ == '__main__':
    config, metrics = parse_log('DP_PushT.log')
    write_js(config, metrics, 'training_data.js')
    print('Done!')
